# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Use `pre-commit install` to install the hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: '22.6.0'
    hooks:
    -   id: black
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
    -   id: codespell
        args: ["--skip=*.ipynb,*.sgf,*.sgfs"]
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
-   repo: https://github.com/mattseymour/pre-commit-pytype
    rev: '2022.4.26'
    hooks:
    -   id: pytype
        args: []
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
    -   id: shellcheck
        args: ["--severity=warning"]

