# Launches a baseline attack on ELF OpenGo.
#
# Launch command:
#   ./compose/transfer/launch.sh baseline-attack-vs-elf up
version: "3"

services:
  # This service may throw a benign EOFError at the end of the job.
  victim:
    image: humancompatibleai/goattack:elf
    build:
      context: ${HOST_REPO_ROOT}/engines/elf
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
    command: >
      sh -c "
        socat TCP4-LISTEN:80,reuseaddr EXEC:'./run-gtp.sh --verbose' \
        2>&1 | tee --append /outputs/victim.log
      "
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["${GPU:-0}"]
  baseline_attack:
    image: humancompatibleai/goattack:cpp
    build:
      context: ${HOST_REPO_ROOT}
      dockerfile: ${HOST_REPO_ROOT}/compose/cpp/Dockerfile
      target: prod
    depends_on:
      - victim
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
      - type: bind
        source: ${HOST_REPO_ROOT}
        target: /go_attack
        read_only: true
    command:
      sh -c "
        python3 -u /go_attack/scripts/baseline_attack.py
        --engine elf
        --executable /go_attack/compose/transfer/connect-to-victim.sh
        --log-dir /outputs/sgfs
        --num-games ${NUM_GAMES}
        --verbose
        2>&1 | tee --append /outputs/attack.log
      "
