# Launches a baseline attack on ELF OpenGo.
#
# Command:
#   docker-compose -f compose/transfer/baseline-attack-vs-elf.yml --project-name baseline-vs-elf up
version: "3"

services:
  victim:
    image: humancompatibleai/goattack:elf
    build:
      context: ../../engines/elf
    volumes:
      - type: bind
        source: ../../engines/elf/gtp-defaults.sh
        target: /ELF/scripts/elfgames/go/gtp-defaults.sh
    # TODO where to save logs? how does victimplay do it?
    command: [
      # Exposes ELF on port 80.
      "socat", "TCP4-LISTEN:80,reuseaddr", "EXEC:'./gtp-defaults.sh'"
    ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["0"]
  baseline_attack:
    image: humancompatibleai/goattack:cpp
    build:
      context: ../..
      dockerfile: ../compose/cpp/Dockerfile
      target: prod
    depends_on:
      - victim
    volumes:
      - type: bind
        source: ../..
        target: /go_attack
    # TODO(tomtseng) move num-games into an env. update file header comment
    # after to include env file
    # TODO(tomtseng) Ideally the env file should have a verbose toggle that can
    # toggle verboseness on both baseline_attack and the victim
    # TODO where to save logs? how does victimplay do it?
    command: [
      "python3", "-u", "/go_attack/scripts/baseline_attack.py",
      "--config", "/go_attack/configs/katago/baseline_attack.cfg",
      "--executable", "/engines/connect-to-victim.sh", "--engine", "elf",
      "--no-suicide", "--models", "/dev/null", "--num-games", "2", "--verbose",
    ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["0"]
