# Launches games between KataGo and ELF OpenGo.
#
# Launch command:
#   ./compose/transfer/launch.sh --katago-model <model> --katago-victim-model <victim-model> katago-vs-elf up
version: "3"

services:
  # This service may throw a benign EOFError at the end of the job.
  victim:
    image: humancompatibleai/goattack:elf
    build:
      context: ${HOST_REPO_ROOT}/engines/elf
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
    command: >
      sh -c "
        socat TCP4-LISTEN:80,reuseaddr EXEC:'./run-gtp.sh --verbose' \
        2>&1 | tee --append /outputs/victim.log
      "
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["${GPU:-0}"]
  katago:
    image: humancompatibleai/goattack:cpp
    build:
      context: ${HOST_REPO_ROOT}
      dockerfile: ${HOST_REPO_ROOT}/compose/cpp/Dockerfile
      target: prod
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
      - type: bind
        source: ${HOST_REPO_ROOT}/configs
        target: ${HOST_REPO_ROOT}/configs
        read_only: true
      - type: bind
        source: ${KATAGO_MODEL}
        target: ${KATAGO_MODEL}
        read_only: true
      - type: bind
        source: ${KATAGO_VICTIM_MODEL}
        target: ${KATAGO_VICTIM_MODEL}
        read_only: true
    # ELF does not accept suicide moves, so we set multiStoneSuicideLegal=false.
    command: >
      sh -c "
        socat TCP4-LISTEN:80,reuseaddr \
        EXEC:\"/engines/KataGo-custom/cpp/katago gtp \
          -config ${KATAGO_CONFIG} \
          -model ${KATAGO_MODEL} \
          -victim-model ${KATAGO_VICTIM_MODEL} \
          -override-config multiStoneSuicideLegal=false \
          \" \
        2>&1 | tee --append /outputs/katago.log
      "
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["${GPU:-0}"]
  twogtp:
    image: humancompatibleai/goattack:twogtp
    build:
      context: ${HOST_REPO_ROOT}
      dockerfile: ${HOST_REPO_ROOT}/compose/transfer/twogtp/Dockerfile
    depends_on:
      - victim
      - katago
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
    command:
      sh -c "
        mkdir --parents /outputs/sgfs &&
        bin/gogui-twogtp
          -black 'nc victim 80' -white 'nc katago 80'
          -alternate -auto -games ${NUM_GAMES} -komi ${KOMI} -maxmoves 1600
          -sgffile /outputs/sgfs/game -verbose
        2>&1 | tee --append /outputs/twogtp.log
      "
