# To launch run the following command from the directory containing this file:
#     kubectl create -f vit-bot.yaml
# Make sure to set the credentials of the bot accordingly.
# Only one copy of the bot can run at a time on one account!
# You can set the room the bot is in by manually logging in as the bot on KGS,
# and navigating to the room you want the bot to be in. When the bot reconnects
# it will join the room you were in.
apiVersion: batch/v1
kind: Job
metadata:
  name: vit-kgs-bot
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true # The job must start suspended kueue will start it when it is admitted
  backoffLimit: 9001
  template:
    spec:
      priorityClassName: normal-batch
      restartPolicy: OnFailure
      containers:
      - name: gtp
        image: humancompatibleai/goattack:b2fb839-cpp-kgs
        args: [
          "name=ViTKata001",
          "password=???",
          "gameNotes=Barely superhuman Vision Transformer bot.",
          "rules.time=15:00+5x0:30",
        ]
        resources:
          limits:
            memory: 80Gi
            nvidia.com/gpu: "2"
          requests:
            cpu: 32
            nvidia.com/gpu: "2"
