# Launches a container for easy debugging the KataGo C++ code.
#
# See https://stackoverflow.com/a/52641495/1337463 for documentation on how to
# run commands with `sh -c`.
#
# Launch command on svm (run from repo root).
# docker-compose -f compose/cpp-debug.yml --env-file compose/cpp-debug.env up

version: "3"

services:
  cpp:
    image: humancompatibleai/goattack:cpp
    build:
      context: ..
      dockerfile: ./compose/cpp/Dockerfile
      target: build-deps
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
      - type: bind
        source: ${HOST_CONFIG_DIR}
        target: /configs
        read_only: true
      - type: bind
        source: ${GO_ATTACK_ROOT_DIR}
        target: /garoot
        read_only: true
      - type: bind
        source: ${HOST_CPP_DIR}
        target: /cpp
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["2"]
    cap_add:
      - SYS_PTRACE  # to enable gdb debugging
    tty: true
    stop_grace_period: 60s
