# KataGo victimplay training.
# Based off of selfplay training documented at
# https://github.com/lightvector/KataGo/blob/master/SelfplayTraining.md.
#
# See https://stackoverflow.com/a/52641495/1337463 for documentation on how to
# run commands with `sh -c`.
#
# Launch command (run from repo root):
# docker-compose -f compose/victimplay.yml --env-file compose/victimplay.env up

version: "3"

services:
  victimplay:
    image: humancompatibleai/goattack:cpp
    build:
      context: ..
      dockerfile: ./compose/cpp/Dockerfile
      target: prod
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
      - type: bind
        source: ${HOST_MODEL_DIR}
        target: /models
      - type: bind
        source: ${HOST_CONFIG_DIR}
        target: /configs
    command: >
      sh -c "
        cd /engines/KataGo-custom &&
        ./cpp/katago victimplay \
        -output-dir /outputs/selfplay \
        -models-dir /outputs/models \
        -nn-victim-file ${VICTIM_FILE} \
        -config ${VICTIMPLAY_CONFIG}
      "
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["1", "2", "3", "4", "5", "6", "7"]
    cap_add:
      - SYS_PTRACE
