apiVersion: batch/v1
kind: Job
metadata:
  generateName: cyclic-reattack2-vp-
  labels:
    kueue.x-k8s.io/queue-name: preemptable-batch
spec:
  suspend: true # The job must start suspended; kueue will start it when it is admitted
  template:
    spec:
      containers:
      - command:
        - /go_attack/kubernetes/victimplay.sh
        - --warmstart
        - tony-cyclic-reattack2-20230901
        - shared
        name: victimplay
        image: humancompatibleai/goattack:f349e7e-cpp
        resources:
          limits:
            cpu: 10
            memory: 52Gi
            nvidia.com/gpu: 1
          requests:
            cpu: 6
            memory: 30Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /shared
          name: go-attack
      restartPolicy: Never
      volumes:
      - name: go-attack
        persistentVolumeClaim:
          claimName: go-attack
